curl -X POST "http://localhost:8080/device?groupId=1&deviceId=1"
curl -X POST "http://localhost:8080/device?groupId=1&deviceId=2"
curl -X POST "http://localhost:8080/device?groupId=1&deviceId=3"
curl "http://localhost:8080/devicegroup?groupId=1"
curl "http://localhost:8080/temperature?groupId=1"
curl -X POST "http://localhost:8080/temperature?groupId=1&deviceId=3&temperature=3"
curl "http://localhost:8080/temperature?groupId=1"
curl -X POST "http://localhost:8080/temperature?groupId=1&deviceId=2&temperature=2"
curl -X POST "http://localhost:8080/temperature?groupId=1&deviceId=1&temperature=0"
curl -X POST "http://localhost:8080/temperature?groupId=1&deviceId=1&temperature=1"
curl "http://localhost:8080/temperature?groupId=1"
echo "Temperature for Device 1"
curl "http://localhost:8080/temperature?groupId=1&deviceId=1"
echo ""